### ISSUE TITLE
Expose how big the data would be in errors.

### ISSUE THREAD

**Issue by cheako** [slowli/const-decoder#12]
I had used values like 4 and 9999 on something that was ~42 bytes.  I was expecting to be told the size of the base64 value.

hex literals not do base64 and binary_macros is so old it may not work on nightly.  BTW I used `concat!()` to join sections for large blobs, it felt clumsy.

**Comment by slowli** [comment]
Regarding `concat!`, if I understand the problem correctly, you can use [`SkipWhitespace`](https://slowli.github.io/const-decoder/const_decoder/struct.SkipWhitespace.html):

```rust
const KEY: [u8; 64] = SkipWhitespace(Decoder::Hex).decode(b"
    9e55d1e1 aa1f455b 8baad9fd f9755036 55f8b359 d542fa7e
    4ce84106 d625b352 06fac1f2 2240cffd 637ead66 47188429
    fafda9c9 cb7eae43 386ac17f 61115075
");
```

Regarding the size of the encoded value, this is a more complex issue to solve. The problem here is that panics in const contexts cannot include format args; code like `panic!("real length: {len}")` in a `const fn` does not compile with the following error message: "cannot call non-const formatting macro in constant functions". I'll think about workarounds, but I haven't managed to find one previously.
